### PR TITLE
Pattern Checker: Fix optional groups giving a null instead of an empty string

### LINKED ISSUE #237: Pattern Checker: Optional groups yield "null" instead of an empty string
### Steps to reproduce

1. Add the following into the Pattern Checker config:
```json
[
  "Optional groups": {
    "regex": "^https:\/\/test\\.invalid\/(.+)?$",
    "excludeRegex": "^https:\/\/test\\.invalid\/exclude\/",
    "replacement": "https:\/\/test.invalid\/exclude\/$1"
  }
]
```
2. Open https://test.invalid/
3. Apply the pattern

### Expected behavior

The URL gets transformed into https://test.invalid/exclude/

### Actual behavior

The URL gets transformed into https://test.invalid/exclude/null

### URLCheck version

2.11

### Android version

Android 9

### Android Custom/Specific ROM or Device

OxygenOS 9.0.10

### Other details

I encountered this bug through this monstrosity that adds `?useskin=vector` to links for wiki.archlinux.org:
```json
[
  "Use old skin for Arch Linux Wiki": {
    "regex": "^https?:\/\/wiki\\.archlinux\\.org\/([^#?]*?)(?:\\?([^#]+))?(#.+)?$",
    "excludeRegex": "^https?:\/\/wiki.archlinux.org\/.*[?&]useskin=",
    "replacement": "https:\/\/wiki\\.archlinux\\.org\/$1?useskin=vector&$2$3",
    "automatic": true
  }
]
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by the-blank-x**
Fixes #237

### CODE REVIEW

File: app/src/main/java/com/trianguloy/urlchecker/modules/list/PatternModule.java [hunk 1]
```diff
@@ -225,4 +228,100 @@ public Message(String pattern) {
...
+    private static int appendReplacement(String text, Matcher matcher, StringBuffer sb, String replacement, int appendPos) {
+        // Copied from https://android.googlesource.com/platform/libcore/+/refs/heads/android13-release/ojluni/src/main/java/java/util/regex/Matcher.java#714
+        sb.append(text.substring(appendPos, matcher.start()));
+        appendEvaluated(matcher, sb, replacement);
+        int newAppendPos = matcher.end();
+
+        return newAppendPos;
+    }
+
+    @TargetApi(Build.VERSION_CODES.O)
```
Comment (TrianguloY) [inline app/src/main/java/com/trianguloy/urlchecker/modules/list/PatternModule.java:263]: Is this necessary? 🤔

File: app/src/main/java/com/trianguloy/urlchecker/modules/list/PatternModule.java [hunk 2]
```diff
@@ -225,4 +228,100 @@ public Message(String pattern) {
             this.pattern = pattern;
         }
     }
+
+    /**
+     * On Android 10 and under, optional groups may yield a "null" in the replacement output instead of an empty string.
+     * Therefore, we just copy the implementation from newer versions
+     * https://github.com/TrianguloY/UrlChecker/issues/237
+     */
+    private static String replaceAll(String text, Pattern pattern, String replacement) {
```
Comment (TrianguloY) [inline app/src/main/java/com/trianguloy/urlchecker/modules/list/PatternModule.java:237]: Is it possible to place an early-return-if here to call the original unmodified replaceAll if we are on an android version where the fix is already native?

File: app/src/main/java/com/trianguloy/urlchecker/modules/list/PatternModule.java [hunk 3]
```diff
@@ -158,7 +161,7 @@ public void onModifyUrl(UrlData urlData, JavaUtils.Function<UrlData, Boolean> se
 
                     if (replacement != null) {
                         // replace url
-                        message.newUrl = url.replaceAll(regex, replacement);
+                        message.newUrl = replaceAll(url, regex, replacement);
```
Comment (TrianguloY) [inline app/src/main/java/com/trianguloy/urlchecker/modules/list/PatternModule.java:164]: Since this is an (impressive) hax, please move all the new logic to a new class (maybe utils.RegexpFix? Not sure).
In any case, this line here should call that class, and that's it.

**Review by TrianguloY — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/trianguloy/urlchecker/modules/list/PatternModule.java (hunk 1 above)
Comment (the-blank-x) [reply app/src/main/java/com/trianguloy/urlchecker/modules/list/PatternModule.java:263]: `lintAlpha` gave me an error for not doing so

File: app/src/main/java/com/trianguloy/urlchecker/modules/list/PatternModule.java (hunk 2 above)
Comment (the-blank-x) [reply app/src/main/java/com/trianguloy/urlchecker/modules/list/PatternModule.java:237]: Sure

**Comment by TrianguloY** [comment]
Perfect! Thanks! 
Just let me check a few things first with my computer (and also I want to see how you fixed the error I had). I'll tell you if I need anything else.

Good job!

**Comment by TrianguloY** [comment]
Finally!

I was able to review this. Apparently my version failed because I wasn't copying all the required code, like yours.

I validated it, but since this is still a big hack, I added a setting to disable it (just in case, the fix is enabled by default).

Again, thank you! Nice work! 

merged
